''' holds unknown list'''

other_list = [
'000_60-01-01-99-131',
'3/4_marker_light_single_blue_diode_led_truck_trailer_rv_55bc_hot_aux_use',
'70x120mm',
'advent_calendar',
'amon',
'black_leather_assassins_blades_black',
'bold',
'cat_tower',
'chow_mein',
'christmas_dragon_2021',
'crystal_moss-_glass',
'custom_amount',
'custom_amount_-_deposit',
'ds:_halloween_2022',
'dungeon_scrawlers',
'egift_card',
'fireworks',
'gamemaster',
'gazebo',
'gift_card',
'hydro_pack',
'lord_of_the_jungle',
'lost_code',
'mega_weapons_pack',
'moraia',
'most_delicious.',
'nan',
'pre_release',
'prerelease',
'prerelease_event',
'raffle_ticket',
'shipping',
'spike_present',
'the_dark_of_host_island_set',
'tkay',
'wet_erase_markers']

game_room_list = [
'game_room',
'room_rental']
